# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=None, max_length=200)),
                ('is_active', models.IntegerField(default=1)),
                ('share', models.IntegerField(default=10)),
                ('portal_name', models.CharField(max_length=200)),
                ('portal_type', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.DateTimeField(auto_now_add=True)),
                ('email_activated', models.IntegerField(default=0)),
            ],
        ),
    ]
