# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
