# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-05-30 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_responsable_hash_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('request_type', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.IntegerField(default=0)),
                ('paid_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
