# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-05-31 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_payment_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_request',
            name='account',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='payment_request',
            name='agency',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='payment_request',
            name='bank',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='payment_request',
            name='cpf',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='payment_request',
            name='email_paypal',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='payment_request',
            name='name_owner',
            field=models.CharField(default='', max_length=400),
        ),
    ]
